---
- name: Create guacamole container
  community.docker.docker_container:
    name: guacamole
    image: flcontainers/guacamole
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/guacamole/config:/config"
    ports:
      - 8084:8080
