---
- name: Create jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      JELLYFIN_PublishedServerUrl: "{{ ip_address }}"
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
      - "{{ data_dir }}/media/Multimedia:/data/"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
