---

- name: Create qbittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    restart_policy: unless-stopped
    state: started
    ports:
      - "6881:6881"
      - "6882:6882"
      - "6881:6881/udp"
    volumes:
      - "{{ docker_dir }}/qbittorrent/config:/config"
      - "{{ data_dir }}/torrents:/data/torrents"
      - "{{ docker_dir }}/qbittorrent/vuetorrent:/vuetorrent"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      WEBUI_PORT: 6882

